### ISSUE TITLE
Sketchup2022 crashes when loading Openstudio plugin 1.7

### ISSUE THREAD

**Issue by Thickestman** [openstudiocoalition/openstudio-sketchup-plugin#143]
Hi there, 
I have been trying to load Openstudio plugin 1.7 in sketchup Pro 2022 but it has been crashing. what can i do to fix this issue?

**Comment by Thickestman** [comment]
This happened on windows 11

**Comment by macumber** [comment]
Thanks @Thickestman, which version of the OpenStudio Application did you point your plug-in at?  If you tried to use OpenStudio Application 1.8.0 higher with SketchUp 2022 that would crash due to the incompatible Ruby versions.  You can see the version compatibility matrix at https://github.com/openstudiocoalition/OpenStudioApplication/wiki/OpenStudio-Application-Version-Compatibility-Matrix

I added some code in https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.8.0-rc.2 that will prevent suggesting an incompatible version of the OpenStudio Application when users first install the plug-in on a new version of SketchUp.

**Comment by Thickestman** [comment]
Thank you @macumber I was using OpenStudio v1.7.2. Just few minutes ago, I uninstalled the SketchUp 2022 and the OpenStudio, then deleted the files from program file. I installed both SketchUp 2022 and Openstudio v1.7.2 after which I loaded the SketchUp plugin v1.7.0 again and it worked fine.
However, I tried to check if the Building Component Library functionality is working by going to Components & Measures / Find Measures then Reporting > QAQC  > OpenStudio Results and download. The OpenStudio Results boxes are not active and cannot be downloaded. It says "**This measures requires a newer version of OpenStudio**"
<img width="613" alt="Screen 2" src="https://github.com/user-attachments/assets/37d0eecb-28e7-49e7-af50-0c7f17e206cf">
<img width="613" alt="Screen 1 " src="https://github.com/user-attachments/assets/fd314d66-0461-46d3-bc25-a7dcdbc85dc1">
