### ISSUE TITLE
OS SketchUp Plug-in’s Luminaire Tool

### ISSUE THREAD

**Issue by tijcolem** [openstudiocoalition/openstudio-sketchup-plugin#3]
The OS SketchUp Plug-in’s Luminaire Tool functionality is no longer working when using the toolbar and this appears to be deliberate as the ability to create load “definitions” (people/lights/equipment) was removed from the SketchUp Plugin.  

This may have been forgotten to remove from the toolbar? If so, it can be safely removed.

**Comment by eomere** [comment]
To elaborate on Tim's issue here; the Luminaire Tool icon will add Luminaires to the model. Typically, after a Luminaire is added to a model, its *Power Usage* and *Photometric Description* will be defined. Within this Plugin, a User would do this inside the OpenStudio Inspector. **The issue here is that the OpenStudio Inspector does not support Luminaires**. Hence, one is unable to define the aforementioned characteristics.

**Comment by macumber** [comment]
This was removed when we moved editing of all space loads (including luminaires) to the OS Application.  The luminaire can be placed and moved in the SketchUp Plug-in but the energy related properties are edited in the Load Definitions and Space/Loads tabs in the OS Application.

Ideally you could choose an existing Luminaire Definition when placing a Luminaire.  However, you can reassign luminaire definitions in the OS Application so there is a work around.
