### ISSUE TITLE
Sketchup OpenStudio Plugin - weird sized icons on the app

### ISSUE THREAD

**Issue by Maharshi-Pathak** [openstudiocoalition/openstudio-sketchup-plugin#94]
For fresh installations of SketchUp and Openstudio plugin, I am seeing this weird issue on some of my Windows systems.  Is this a bug or I need to change something on my system? 
![image](https://user-images.githubusercontent.com/64644720/135534344-9cfd324c-d729-4b2d-b99e-d1686a85a8b7.png)

**Comment by macumber** [comment]
That is strange.  Do you have View->Toolbars->Options->Large Icons selected? What is your screen size and resolution so I can try to reproduce? 

It seems like this is likely related to this thread: https://forums.sketchup.com/t/size-of-menu-and-icons/12767/5

This is the relevant SketchUp Ruby API: https://ruby.sketchup.com/UI/Command.html#large_icon-instance_method

We might be able to simply resize our large icons to 32x32 pixels, https://github.com/openstudiocoalition/openstudio-sketchup-plugin/tree/develop/plugin/openstudio/lib/resources/icons.  The better way to do this would be to recreate them in SVG format, I am not skilled enough to do that.

**Comment by macumber** [comment]
Should be fixed with https://github.com/openstudiocoalition/openstudio-sketchup-plugin/pull/96

I made a 1.3.0-rc1 release, https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/tag/v1.3.0-rc1, and there is a rbz file at https://github.com/openstudiocoalition/openstudio-sketchup-plugin/releases/download/v1.3.0-rc1/openstudio-sketchup-plugin.rbz if you are able to try it out to make sure the fix worked
